title : __yeoo
tagline: lost in world
author :
  name : p yeoo
  email : yeoo@outlook.com
  github : yeoo
  twitter : yeoo
  feedburner : yeoo

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.html  
